### ISSUE TITLE
Bug Report: Component Interface Generation Mismatch

### ISSUE THREAD

**Issue by masachetti** [BayBreezy/strapi-plugin-gen-types#22]
The plugin currently generates component interfaces using the category name instead of the component name. This causes a type mismatch when content types reference component fields, as the content type definitions correctly use component names.

To reproduce, I created a category called 'Category' and a component called 'Component' in the 'Category' category. This is the output.

Types file generated:

![Types file generated](https://github.com/user-attachments/assets/20de1ddd-deb9-494c-8b26-c19ba0d15431)

The component JSON schema:
```json
{
  "collectionName": "components_category_components",
  "info": {
    "displayName": "Component"
  },
  "options": {},
  "attributes": {
    "component_name": {
      "type": "string"
    }
  }
}
```

**Comment by masachetti** [comment]
I cloned the repository and found a quick solution. The issue can be fixed by changing how we generate component model names - using the file names instead of folder names.

https://github.com/BayBreezy/strapi-plugin-gen-types/blob/ba2093a5c6f964f63fa094c6830afbfdd6502179/server/src/services/service.ts#L220-L223

```javascript
componentSchemaFiles.forEach((schemaFile) => {
      const schemaJson = fs.readFileSync(schemaFile, "utf-8");
      const schema: StrapiSchema = destr(schemaJson);
      const modelName = path.parse(schemaFile).name; // Use parent folder + file name as model name
```

However, this raises a consideration: If two components share the same name but exist in different categories, we'll encounter naming conflicts in the generated types. To prevent this, we should prefix the component types with their category names.

We can do this by replacing the component model name for this:
```javascript
const modelName = `${path.basename(path.dirname(schemaFile))}.${path.parse(schemaFile).name}`;
```
And change how the `generateTypeForAttribute` builds the type name for components attributes.
https://github.com/BayBreezy/strapi-plugin-gen-types/blob/ba2093a5c6f964f63fa094c6830afbfdd6502179/server/src/services/service.ts#L80-L81
Changes for 
```javascript
case "component":
        const componentName = _.upperFirst(_.camelCase(attribute.component));
```

**Comment by BayBreezy** [comment]
@masachetti Thanks for taking the time to review this and coming up with a solution 😊. Appreciate it.
